<a href="https://colab.research.google.com/github/syed-khader/learning-python-libraries/blob/main/pandasforgithub.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy is used for mathamatical and scientific computations.
pandas is to structure the data and label the data

#pandas
-> it is a open source library of python
used for data analysis

-> pandas helps to performs :-
* data manipulation
* data transfromation
* data handling
* data cleaning
* data exploration

-> pandas stands for 'panel data structure'
which is a term used for statistics for multidimensional structured data.

-> pandas deals with two data structures i.e
1. series
2. dataframe


## limitation of numpy
numpy is also used in data analysis ie-
data cleaning, manipulating, transforming but there are certain limitations of it:
1. numpy stores data in homogenous
2. numpy is not having any structure to store the data

-> because of these limitations python has introduced pandas

In [52]:
'''
before using pandas we need to install it
syntax--> pip install pandas

after installing we need to import the library to the file
syntax--> import pandas as pd
'''
import pandas as pd

# series
* it is a 1-Dimensional label data structure.
* it has a single column of data.
* it is like a 1D array.

In [53]:
#creating a series
#syntax--> pd.series(1D array coll,name='col name')

snacks=pd.Series(['sandwich','momos','shawarma','samosa','bhelpuri','kerala chips','chowmein','mancurian'],name="snacks",index=[1,2,3,4,5,6,7,8])
snacks

1        sandwich
2           momos
3        shawarma
4          samosa
5        bhelpuri
6    kerala chips
7        chowmein
8       mancurian
Name: snacks, dtype: object

In [54]:
# create two series
# one list of your friends
# list of destinations you want to visit before you die

friends=pd.Series(['asim','atif','amir','harsh','shahank','jhon'],name="friends",index=[1,2,3,4,5,6])
friends

list_of_places=pd.Series(['kashmir','goa','sweden','amarica','japan',45],name="places",index=[1,2,3,4,5,6])
list_of_places

1    kashmir
2        goa
3     sweden
4    amarica
5      japan
6         45
Name: places, dtype: object

In [55]:
# Accessing values from series
#syntax--> var[index]
list_of_places[2]

#accessing multiple index position
list_of_places[[2,3,1]]

#access multiple values in a seq manner--> slicing
#syntax--> var[si:ei+-1:step]
list_of_places[2:4]

3     sweden
4    amarica
Name: places, dtype: object

In [56]:
snacks.ndim
snacks.size
snacks.shape
snacks.dtype

# we can perform all the attributes if array on series

dtype('O')

In [57]:
# difference between series and array
'''
        array                                     series
1. it belongs to numpy                  1. it belongs to pandas
2. string is treated as string          2. string is treated as object
3. np.array(coll)                       3. pd.Series(coll)
4. we can create N dimension arrays     4. it can be only 1D
5. it can only store homogenous         5. can store heterogenous data
'''

'\n        array                                     series\n1. it belongs to numpy                  1. it belongs to pandas\n2. string is treated as string          2. string is treated as object\n3. np.array(coll)                       3. pd.Series(coll)\n4. we can create N dimension arrays     4. it can be only 1D\n5. it can only store homogenous         5. can store heterogenous data\n'

## DataFrame

-> It is a 2-Dimensional datastructure of pandas.

-> It stores the data in a tabular manner having rows and columns.

-> It is a collection series

In [58]:
#Creating a dataframe
#Syntax-->pd.DataFrame(Dictionary)

df=pd.DataFrame({'Name':['Rahul','Raj','Harish','Sunil','Ganesh'],
                 'City':['KOL','MP','DEL','BBSR','MUM'],
                 'Age':[23,45,24,21,67]})
df

#Creating dataframe using nested list
#Syntax-->pd.DataFrame(data,columns=[col1,col2,...coln])

data=[['Manchurian','full',120],
      ['Chowmein','half',90],
      ['Samosa','half',20],
      ['Egg puff','full',40],
       ['Bonda',None,45]]

df1=pd.DataFrame(data,columns=['Item','Quantity','Price'])
df1

         Item Quantity  Price
0  Manchurian     full    120
1    Chowmein     half     90
2      Samosa     half     20
3    Egg puff     full     40
4       Bonda     None     45

In [59]:
'''Create a dataframe having 6 rows and colums like Name,Place,
Hobbie,Aim,Fav destination,Fav food '''

#Accessing a particular column data
#Syntacx-->df[colname]
df1['Quantity'][1]

df1['Quantity'].unique()  #Gives all the unique values present in column
df1['Quantity'].count()   #gives total number of non null values in a column
df1['Quantity'].value_counts()  #count of the unique values
df1['Quantity'].nunique()   #gives count of the unique values present in column
0
df1['Item'].nunique()
df1['Quantity'].count()
df1['Quantity'].nunique()
var=df1['Quantity'].value_counts()


#Access the index values from the series
#Syntax-->var.index
snacks.index

#Access the values from the series
#Syntax-->var.values
snacks.values

array(['sandwich', 'momos', 'shawarma', 'samosa', 'bhelpuri',
       'kerala chips', 'chowmein', 'mancurian'], dtype=object)

In [60]:
# sort the dataframe based on column
# syntax--> df.sort_values(by=col)

df1.sort_values(by='Item')
df.sort_values(['City','Age'])

     Name  City  Age
3   Sunil  BBSR   21
2  Harish   DEL   24
0   Rahul   KOL   23
1     Raj    MP   45
4  Ganesh   MUM   67

In [61]:
# Dataframe Attributes

df.shape
df.ndim
df.size
df.dtypes

#advantages of dataframes
'''
-> row labels
-> column labels
-> sorting
-> tabular structure
-> handling missing values
-> and new columns
-> filering
-> merging
'''

'\n-> row labels\n-> column labels\n-> sorting\n-> tabular structure\n-> handling missing values\n-> and new columns\n-> filering\n-> merging\n'

In [62]:
#info()-> infromation regarding the data present in dataframe
#syntax -> df.info()
df.info()

# head()--> gives the data from the top of the dataframe
#syntax--> df.head(n), n no of rows
# by default head() gives top 5 rows
df.head(2)

#tail()--> gives the data from the bottom of the dataframe
#syntax--> df.tail(n), n no of rows
# by default tail() gives bottom 5 rows
df.tail(2)

# describe() -- > gives the statistical information of the dataframe
# it works only on numarical column
# syntax --> df.describe()

# to include object information
# syntax--> df.describe(include=object)
df.describe(include=object)


# unique() fucntion --> gives the unique values for a particular column
# syntax--> df['col'].unique()
df['Name'].unique()

# df.columns is used to give column names in our data frame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   City    5 non-null      object
 2   Age     5 non-null      int64
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

array(['Rahul', 'Raj', 'Harish', 'Sunil', 'Ganesh'], dtype=object)

In [63]:
prod=pd.DataFrame({'product': ['mobile phone','laptop','AC','washing machine','TV','air fryer','kettle'],'price':[35000,60000,50000,10000,60000,4000,1000]})
prod

# adding a new column
#syntax--> df[new_col]=value

prod['category']='electronics'
prod
prod['category']=['phones','electronics','appliance','appliance','appliance','appliance','appliance']
prod


#dropping a column
#syntax--> df.drop(col,axis=1,inplace=True)
prod.drop('category',axis=1,inplace=True)
prod

#inplace =True will modify the orignal dataframe/data source

#dropping a particular row using index
#syntax-> df.drop(index)
elec=prod.drop(3)
elec

#rename a column
# var={'old col':'new col'}
#df.rename(columns=var)

data={'price':'MRP'}
prod.rename(columns=data,inplace=True)
prod

           product    MRP
0     mobile phone  35000
1           laptop  60000
2               AC  50000
3  washing machine  10000
4               TV  60000
5        air fryer   4000
6           kettle   1000

In [64]:
# Create a Hospital Management DataFrame with:


hosp=pd.DataFrame({'Patient_id':[101,102,103,104],
                   'Name':['Atul','Reshma','Sunil','Gujju'],
                   'Age':[23,21,34,22],
                   'Gender':['Male','Female','Male','Trans'],
                   'Disease':['Fever','TB','Cancer','COVID'],
                   'Doctor':['Dr Suresh','Dr Ram','Dr anjali','Dr Akash'],
                   'Room No':[34,2,3,56],
                   'Bill Amount':[20000,134100,34000,5600]})
# Perform the following:
# Display the first five rows.
# Display only Name and Bill_Amount.
# Print shape, size, columns, index, and data types.
# Add an Insurance_Status column.
# Increase all Bill_Amount values by ₹2,000.
# hosp.rename(columns={'Bill Amount':'Total Bill'},inplace=True)
# hosp.drop('Insurance_Status',axis=1,inplace=True)
# Display the underlying NumPy array using values.

hosp.head(5)

   Patient_id    Name  Age  Gender Disease     Doctor  Room No  Bill Amount
0         101    Atul   23    Male   Fever  Dr Suresh       34        20000
1         102  Reshma   21  Female      TB     Dr Ram        2       134100
2         103   Sunil   34    Male  Cancer  Dr anjali        3        34000
3         104   Gujju   22   Trans   COVID   Dr Akash       56         5600

In [65]:
hosp[['Name','Bill Amount']]

     Name  Bill Amount
0    Atul        20000
1  Reshma       134100
2   Sunil        34000
3   Gujju         5600

In [66]:
# Print shape, size, columns, index, and data types.
print(hosp.shape)
print(hosp.size)
print(hosp.columns)
print(hosp.index)
print(hosp.dtypes)

(4, 8)
32
Index(['Patient_id', 'Name', 'Age', 'Gender', 'Disease', 'Doctor', 'Room No',
       'Bill Amount'],
      dtype='object')
RangeIndex(start=0, stop=4, step=1)
Patient_id      int64
Name           object
Age             int64
Gender         object
Disease        object
Doctor         object
Room No         int64
Bill Amount     int64
dtype: object

In [67]:
# Add an Insurance_Status column.
hosp['Insurance Status']='insured'
hosp

,Patient_id,Name,Age,Gender,Disease,Doctor,Room No,Bill Amount,Insurance Status
0,101,Atul,23,Male,Fever,Dr Suresh,34,20000,insured
1,102,Reshma,21,Female,TB,Dr Ram,2,134100,insured
2,103,Sunil,34,Male,Cancer,Dr anjali,3,34000,insured
3,104,Gujju,22,Trans,COVID,Dr Akash,56,5600,insured

In [68]:
hosp['Bill Amount']+=2000
hosp

,Patient_id,Name,Age,Gender,Disease,Doctor,Room No,Bill Amount,Insurance Status
0,101,Atul,23,Male,Fever,Dr Suresh,34,22000,insured
1,102,Reshma,21,Female,TB,Dr Ram,2,136100,insured
2,103,Sunil,34,Male,Cancer,Dr anjali,3,36000,insured
3,104,Gujju,22,Trans,COVID,Dr Akash,56,7600,insured

In [69]:
hosp.rename(columns={'Bill Amount':'Total Bill'},inplace=True)
hosp.drop('Insurance Status',axis=1,inplace=True)

In [70]:
hosp

   Patient_id    Name  Age  Gender Disease     Doctor  Room No  Total Bill
0         101    Atul   23    Male   Fever  Dr Suresh       34       22000
1         102  Reshma   21  Female      TB     Dr Ram        2      136100
2         103   Sunil   34    Male  Cancer  Dr anjali        3       36000
3         104   Gujju   22   Trans   COVID   Dr Akash       56        7600

In [71]:
# Display the underlying NumPy array using values.
hosp.values
#or
arr=hosp.to_numpy()
arr

array([[101, 'Atul', 23, 'Male', 'Fever', 'Dr Suresh', 34, 22000],
       [102, 'Reshma', 21, 'Female', 'TB', 'Dr Ram', 2, 136100],
       [103, 'Sunil', 34, 'Male', 'Cancer', 'Dr anjali', 3, 36000],
       [104, 'Gujju', 22, 'Trans', 'COVID', 'Dr Akash', 56, 7600]],
      dtype=object)

In [72]:
# to read the dataset syntax-->
#pd.read_file_type('filepath/file link)

#common files to read in dataframe
#pd.read_csv()
#pd.read_excel()
#pd.read_json()
#pd.read_html()
#pd.read_xml()

df=pd.read_csv('titanic.csv')
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [73]:
df.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [74]:
titanic.tail()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,0

In [75]:
df.describe()
df.describe(include=object)

                    name   sex    ticket        cabin embarked
count               1309  1309      1309          295     1307
unique              1307     2       929          186        3
top     Kelly, Mr. James  male  CA. 2343  C23 C25 C27        S
freq                   2   843        11            6      914

In [76]:
df['pclass']

0       1
1       1
2       1
3       1
4       1
       ..
1304    3
1305    3
1306    3
1307    3
1308    3
Name: pclass, Length: 1309, dtype: int64

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   name      1309 non-null   object
 2   sex       1309 non-null   object
 3   age       1046 non-null   float64
 4   sibsp     1309 non-null   int64
 5   parch     1309 non-null   int64
 6   ticket    1309 non-null   object
 7   fare      1308 non-null   float64
 8   cabin     295 non-null    object
 9   embarked  1307 non-null   object
 10  survived  1309 non-null   int64
dtypes: float64(2), int64(4), object(5)
memory usage: 112.6+ KB

In [78]:
#file conversion
# df.to_csv()
# df.to_excel()
# df.to_json()
# df.to_html()

In [81]:
#passengers travelling in pclass 1
p_class_1=df[df['pclass']==1]
p_class_1

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
318,1,"Williams-Lambert, Mr. Fletcher Fellows",male,NaN,0,0,113510,35.0000,C128,S,0
319,1,"Wilson, Miss. Helen Alice",female,31.0000,0,0,16966,134.5000,E39 E41,C,1
320,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S,1
321,1,"Wright, Mr. George",male,62.0000,0,0,113807,26.5500,NaN,S,0
322,1,"Young, Miss. Marie Grice",female,36.0000,0,0,PC 17760,135.6333,C32,C,1

In [86]:
#passengers whose age is less then 30
age_bl_30=df[df['age']>30]
age_bl_30

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
5,1,"Anderson, Mr. Harry",male,48.0,0,0,19952,26.5500,E12,S,1
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,1
7,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S,0
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,1
9,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,0
...,...,...,...,...,...,...,...,...,...,...,...
1286,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C,1
1287,3,"Widegren, Mr. Carl/Charles Peter",male,51.0,0,0,347064,7.7500,NaN,S,0
1290,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1
1298,3,"Wittevrongel, Mr. Camille",male,36.0,0,0,345771,9.5000,NaN,S,0
1301,3,"Youseff, Mr. Gerious",male,45.5,0,0,2628,7.2250,NaN,C,0

In [87]:
#passengers who died in pclass 1

died_in_p1=p_class_1[df['survived']==0]
died_in_p1

/tmp/ipykernel_967/486894873.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  died_in_p1=p_class_1[df['survived']==0]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
2,1,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,0
7,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S,0
9,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,0
...,...,...,...,...,...,...,...,...,...,...,...
312,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C,0
313,1,"Widener, Mr. Harry Elkins",male,27.0,0,2,113503,211.5000,C82,C,0
316,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C,0
318,1,"Williams-Lambert, Mr. Fletcher Fellows",male,NaN,0,0,113510,35.0000,C128,S,0
321,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S,0

In [88]:
#passengers who survied in pclass 1
survied_p1=p_class_1[df['survived']==1]

/tmp/ipykernel_967/1021987339.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  p_class_1[df['survived']==1]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
5,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,26.5500,E12,S,1
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0000,1,0,13502,77.9583,D7,S,1
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0000,2,0,11769,51.4792,C101,S,1
...,...,...,...,...,...,...,...,...,...,...,...
315,1,"Willard, Miss. Constance",female,21.0000,0,0,113795,26.5500,NaN,S,1
317,1,"Williams, Mr. Richard Norris II",male,21.0000,0,1,PC 17597,61.3792,NaN,C,1
319,1,"Wilson, Miss. Helen Alice",female,31.0000,0,0,16966,134.5000,E39 E41,C,1
320,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S,1
322,1,"Young, Miss. Marie Grice",female,36.0000,0,0,PC 17760,135.6333,C32,C,1

In [113]:
count_of_total=p_class_1['survived'].count()
count_of_survived=p_class_1[p_class_1['survived']==1]['survived'].count()
count_of_dead=p_class_1[p_class_1['survived']==0]['survived'].count()
survied_p1_percentage=(count_of_survived/count_of_total)*100

(count_of_dead/count_of_total)*100
survied_p1_percentage

np.float64(61.91950464396285)

In [126]:
#passengers whose age is below 30 or they are male
df[(df['age']<30)|(df['sex']=='male')]
# female passengers who died in titanic
df[(df['sex']=='female')& (df['survived']==0)]
#male passengers from pclass 3 who paid more then 100 as fare
df[(df['sex']=='male')&(df['pclass']==3)&(df['fare']>100)]

Empty DataFrame
Columns: [pclass, name, sex, age, sibsp, parch, ticket, fare, cabin, embarked, survived]
Index: []

In [137]:
#loc()--> labelled indexing
# it is used ti access the records using row index and
#syntax--> df.loc[[row1,row2,row3],[column name]]
'''
In the Python pandas library, df.loc[] is a label-based indexing property used to select,
filter, and update rows and columns in a DataFrame.
Instead of counting numerical positions (like 0, 1, 2),
you use actual row and column names (labels)
'''

df.loc[1,['name']]
df.loc[:,['name']]

#iloc--> integer location
#it is used to access / slice the dataframe using integer values.
#syntax--> df.iloc[row slice,col slice]

df.iloc[2:10:2,2:4]

      sex   age
2  female   2.0
4  female  25.0
6  female  63.0
8  female  53.0