<a href="https://colab.research.google.com/github/syed-khader/learning-python-libraries/blob/main/pandasforgithub.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy is used for mathamatical and scientific computations.
pandas is to structure the data and label the data

#pandas
-> it is a open source library of python
used for data analysis

-> pandas helps to performs :-
* data manipulation
* data transfromation
* data handling
* data cleaning
* data exploration

-> pandas stands for 'panel data structure'
which is a term used for statistics for multidimensional structured data.

-> pandas deals with two data structures i.e
1. series
2. dataframe


## limitation of numpy
numpy is also used in data analysis ie-
data cleaning, manipulating, transforming but there are certain limitations of it:
1. numpy stores data in homogenous
2. numpy is not having any structure to store the data

-> because of these limitations python has introduced pandas

In [2]:
'''
before using pandas we need to install it
syntax--> pip install pandas

after installing we need to import the library to the file
syntax--> import pandas as pd
'''
import pandas as pd

# series
* it is a 1-Dimensional label data structure.
* it has a single column of data.
* it is like a 1D array.

In [3]:
#creating a series
#syntax--> pd.series(1D array coll,name='col name')

snacks=pd.Series(['sandwich','momos','shawarma','samosa','bhelpuri','kerala chips','chowmein','mancurian'],name="snacks",index=[1,2,3,4,5,6,7,8])
snacks

1        sandwich
2           momos
3        shawarma
4          samosa
5        bhelpuri
6    kerala chips
7        chowmein
8       mancurian
Name: snacks, dtype: object

In [4]:
# create two series
# one list of your friends
# list of destinations you want to visit before you die

friends=pd.Series(['asim','atif','amir','harsh','shahank','jhon'],name="friends",index=[1,2,3,4,5,6])
friends

list_of_places=pd.Series(['kashmir','goa','sweden','amarica','japan',45],name="places",index=[1,2,3,4,5,6])
list_of_places

1    kashmir
2        goa
3     sweden
4    amarica
5      japan
6         45
Name: places, dtype: object

In [5]:
# Accessing values from series
#syntax--> var[index]
list_of_places[2]

#accessing multiple index position
list_of_places[[2,3,1]]

#access multiple values in a seq manner--> slicing
#syntax--> var[si:ei+-1:step]
list_of_places[2:4]

3     sweden
4    amarica
Name: places, dtype: object

In [6]:
snacks.ndim
snacks.size
snacks.shape
snacks.dtype

# we can perform all the attributes if array on series

dtype('O')

In [7]:
# difference between series and array
'''
        array                                     series
1. it belongs to numpy                  1. it belongs to pandas
2. string is treated as string          2. string is treated as object
3. np.array(coll)                       3. pd.Series(coll)
4. we can create N dimension arrays     4. it can be only 1D
5. it can only store homogenous         5. can store heterogenous data
'''

'\n        array                                     series\n1. it belongs to numpy                  1. it belongs to pandas\n2. string is treated as string          2. string is treated as object\n3. np.array(coll)                       3. pd.Series(coll)\n4. we can create N dimension arrays     4. it can be only 1D\n5. it can only store homogenous         5. can store heterogenous data\n'

## DataFrame

-> It is a 2-Dimensional datastructure of pandas.

-> It stores the data in a tabular manner having rows and columns.

-> It is a collection series

In [8]:
#Creating a dataframe
#Syntax-->pd.DataFrame(Dictionary)

df=pd.DataFrame({'Name':['Rahul','Raj','Harish','Sunil','Ganesh'],
                 'City':['KOL','MP','DEL','BBSR','MUM'],
                 'Age':[23,45,24,21,67]})
df

#Creating dataframe using nested list
#Syntax-->pd.DataFrame(data,columns=[col1,col2,...coln])

data=[['Manchurian','full',120],
      ['Chowmein','half',90],
      ['Samosa','half',20],
      ['Egg puff','full',40],
       ['Bonda',None,45]]

df1=pd.DataFrame(data,columns=['Item','Quantity','Price'])
df1

         Item Quantity  Price
0  Manchurian     full    120
1    Chowmein     half     90
2      Samosa     half     20
3    Egg puff     full     40
4       Bonda     None     45

In [9]:
'''Create a dataframe having 6 rows and colums like Name,Place,
Hobbie,Aim,Fav destination,Fav food '''

#Accessing a particular column data
#Syntacx-->df[colname]
df1['Quantity'][1]

df1['Quantity'].unique()  #Gives all the unique values present in column
df1['Quantity'].count()   #gives total number of non null values in a column
df1['Quantity'].value_counts()  #count of the unique values
df1['Quantity'].nunique()   #gives count of the unique values present in column
0
df1['Item'].nunique()
df1['Quantity'].count()
df1['Quantity'].nunique()
var=df1['Quantity'].value_counts()


#Access the index values from the series
#Syntax-->var.index
snacks.index

#Access the values from the series
#Syntax-->var.values
snacks.values

array(['sandwich', 'momos', 'shawarma', 'samosa', 'bhelpuri',
       'kerala chips', 'chowmein', 'mancurian'], dtype=object)

In [10]:
# sort the dataframe based on column
# syntax--> df.sort_values(by=col)

df1.sort_values(by='Item')
df.sort_values(['City','Age'])

     Name  City  Age
3   Sunil  BBSR   21
2  Harish   DEL   24
0   Rahul   KOL   23
1     Raj    MP   45
4  Ganesh   MUM   67

In [11]:
# Dataframe Attributes

df.shape
df.ndim
df.size
df.dtypes

#advantages of dataframes
'''
-> row labels
-> column labels
-> sorting
-> tabular structure
-> handling missing values
-> and new columns
-> filering
-> merging
'''

'\n-> row labels\n-> column labels\n-> sorting\n-> tabular structure\n-> handling missing values\n-> and new columns\n-> filering\n-> merging\n'

In [12]:
#info()-> infromation regarding the data present in dataframe
#syntax -> df.info()
df.info()

# head()--> gives the data from the top of the dataframe
#syntax--> df.head(n), n no of rows
# by default head() gives top 5 rows
df.head(2)

#tail()--> gives the data from the bottom of the dataframe
#syntax--> df.tail(n), n no of rows
# by default tail() gives bottom 5 rows
df.tail(2)

# describe() -- > gives the statistical information of the dataframe
# it works only on numarical column
# syntax --> df.describe()

# to include object information
# syntax--> df.describe(include=object)
df.describe(include=object)


# unique() fucntion --> gives the unique values for a particular column
# syntax--> df['col'].unique()
df['Name'].unique()

# df.columns is used to give column names in our data frame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   City    5 non-null      object
 2   Age     5 non-null      int64
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

array(['Rahul', 'Raj', 'Harish', 'Sunil', 'Ganesh'], dtype=object)

In [13]:
prod=pd.DataFrame({'product': ['mobile phone','laptop','AC','washing machine','TV','air fryer','kettle'],'price':[35000,60000,50000,10000,60000,4000,1000]})
prod

# adding a new column
#syntax--> df[new_col]=value

prod['category']='electronics'
prod
prod['category']=['phones','electronics','appliance','appliance','appliance','appliance','appliance']
prod


#dropping a column
#syntax--> df.drop(col,axis=1,inplace=True)
prod.drop('category',axis=1,inplace=True)
prod

#inplace =True will modify the orignal dataframe/data source

#dropping a particular row using index
#syntax-> df.drop(index)
elec=prod.drop(3)
elec

#rename a column
# var={'old col':'new col'}
#df.rename(columns=var)

data={'price':'MRP'}
prod.rename(columns=data,inplace=True)
prod

           product    MRP
0     mobile phone  35000
1           laptop  60000
2               AC  50000
3  washing machine  10000
4               TV  60000
5        air fryer   4000
6           kettle   1000

In [14]:
# Create a Hospital Management DataFrame with:


hosp=pd.DataFrame({'Patient_id':[101,102,103,104],
                   'Name':['Atul','Reshma','Sunil','Gujju'],
                   'Age':[23,21,34,22],
                   'Gender':['Male','Female','Male','Trans'],
                   'Disease':['Fever','TB','Cancer','COVID'],
                   'Doctor':['Dr Suresh','Dr Ram','Dr anjali','Dr Akash'],
                   'Room No':[34,2,3,56],
                   'Bill Amount':[20000,134100,34000,5600]})
# Perform the following:
# Display the first five rows.
# Display only Name and Bill_Amount.
# Print shape, size, columns, index, and data types.
# Add an Insurance_Status column.
# Increase all Bill_Amount values by ₹2,000.
# hosp.rename(columns={'Bill Amount':'Total Bill'},inplace=True)
# hosp.drop('Insurance_Status',axis=1,inplace=True)
# Display the underlying NumPy array using values.

hosp.head(5)

   Patient_id    Name  Age  Gender Disease     Doctor  Room No  Bill Amount
0         101    Atul   23    Male   Fever  Dr Suresh       34        20000
1         102  Reshma   21  Female      TB     Dr Ram        2       134100
2         103   Sunil   34    Male  Cancer  Dr anjali        3        34000
3         104   Gujju   22   Trans   COVID   Dr Akash       56         5600

In [15]:
hosp[['Name','Bill Amount']]

     Name  Bill Amount
0    Atul        20000
1  Reshma       134100
2   Sunil        34000
3   Gujju         5600

In [16]:
# Print shape, size, columns, index, and data types.
print(hosp.shape)
print(hosp.size)
print(hosp.columns)
print(hosp.index)
print(hosp.dtypes)

(4, 8)
32
Index(['Patient_id', 'Name', 'Age', 'Gender', 'Disease', 'Doctor', 'Room No',
       'Bill Amount'],
      dtype='object')
RangeIndex(start=0, stop=4, step=1)
Patient_id      int64
Name           object
Age             int64
Gender         object
Disease        object
Doctor         object
Room No         int64
Bill Amount     int64
dtype: object

In [17]:
# Add an Insurance_Status column.
hosp['Insurance Status']='insured'
hosp

,Patient_id,Name,Age,Gender,Disease,Doctor,Room No,Bill Amount,Insurance Status
0,101,Atul,23,Male,Fever,Dr Suresh,34,20000,insured
1,102,Reshma,21,Female,TB,Dr Ram,2,134100,insured
2,103,Sunil,34,Male,Cancer,Dr anjali,3,34000,insured
3,104,Gujju,22,Trans,COVID,Dr Akash,56,5600,insured

In [18]:
hosp['Bill Amount']+=2000
hosp

,Patient_id,Name,Age,Gender,Disease,Doctor,Room No,Bill Amount,Insurance Status
0,101,Atul,23,Male,Fever,Dr Suresh,34,22000,insured
1,102,Reshma,21,Female,TB,Dr Ram,2,136100,insured
2,103,Sunil,34,Male,Cancer,Dr anjali,3,36000,insured
3,104,Gujju,22,Trans,COVID,Dr Akash,56,7600,insured

In [19]:
hosp.rename(columns={'Bill Amount':'Total Bill'},inplace=True)
hosp.drop('Insurance Status',axis=1,inplace=True)

In [20]:
hosp

   Patient_id    Name  Age  Gender Disease     Doctor  Room No  Total Bill
0         101    Atul   23    Male   Fever  Dr Suresh       34       22000
1         102  Reshma   21  Female      TB     Dr Ram        2      136100
2         103   Sunil   34    Male  Cancer  Dr anjali        3       36000
3         104   Gujju   22   Trans   COVID   Dr Akash       56        7600

In [21]:
# Display the underlying NumPy array using values.
hosp.values
#or
arr=hosp.to_numpy()
arr

array([[101, 'Atul', 23, 'Male', 'Fever', 'Dr Suresh', 34, 22000],
       [102, 'Reshma', 21, 'Female', 'TB', 'Dr Ram', 2, 136100],
       [103, 'Sunil', 34, 'Male', 'Cancer', 'Dr anjali', 3, 36000],
       [104, 'Gujju', 22, 'Trans', 'COVID', 'Dr Akash', 56, 7600]],
      dtype=object)

In [22]:
# to read the dataset syntax-->
#pd.read_file_type('filepath/file link)

#common files to read in dataframe
#pd.read_csv()
#pd.read_excel()
#pd.read_json()
#pd.read_html()
#pd.read_xml()

df=pd.read_csv('https://raw.githubusercontent.com/sam6cyber/Datasets/refs/heads/main/titanic.csv')
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [23]:
df.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [24]:
df.tail()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,0

In [25]:
df.describe()
df.describe(include=object)

                    name   sex    ticket        cabin embarked
count               1309  1309      1309          295     1307
unique              1307     2       929          186        3
top     Kelly, Mr. James  male  CA. 2343  C23 C25 C27        S
freq                   2   843        11            6      914

In [26]:
df['pclass']

0       1
1       1
2       1
3       1
4       1
       ..
1304    3
1305    3
1306    3
1307    3
1308    3
Name: pclass, Length: 1309, dtype: int64

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   name      1309 non-null   object
 2   sex       1309 non-null   object
 3   age       1046 non-null   float64
 4   sibsp     1309 non-null   int64
 5   parch     1309 non-null   int64
 6   ticket    1309 non-null   object
 7   fare      1308 non-null   float64
 8   cabin     295 non-null    object
 9   embarked  1307 non-null   object
 10  survived  1309 non-null   int64
dtypes: float64(2), int64(4), object(5)
memory usage: 112.6+ KB

In [28]:
#file conversion
# df.to_csv()
# df.to_excel()
# df.to_json()
# df.to_html()

In [29]:
#passengers travelling in pclass 1
p_class_1=df[df['pclass']==1]
p_class_1

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
318,1,"Williams-Lambert, Mr. Fletcher Fellows",male,NaN,0,0,113510,35.0000,C128,S,0
319,1,"Wilson, Miss. Helen Alice",female,31.0000,0,0,16966,134.5000,E39 E41,C,1
320,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S,1
321,1,"Wright, Mr. George",male,62.0000,0,0,113807,26.5500,NaN,S,0
322,1,"Young, Miss. Marie Grice",female,36.0000,0,0,PC 17760,135.6333,C32,C,1

In [30]:
#passengers whose age is less then 30
age_bl_30=df[df['age']>30]
age_bl_30

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
5,1,"Anderson, Mr. Harry",male,48.0,0,0,19952,26.5500,E12,S,1
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,1
7,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S,0
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,1
9,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,0
...,...,...,...,...,...,...,...,...,...,...,...
1286,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C,1
1287,3,"Widegren, Mr. Carl/Charles Peter",male,51.0,0,0,347064,7.7500,NaN,S,0
1290,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1
1298,3,"Wittevrongel, Mr. Camille",male,36.0,0,0,345771,9.5000,NaN,S,0
1301,3,"Youseff, Mr. Gerious",male,45.5,0,0,2628,7.2250,NaN,C,0

In [31]:
#passengers who died in pclass 1

died_in_p1=p_class_1[df['survived']==0]
died_in_p1

/tmp/ipykernel_4192/486894873.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  died_in_p1=p_class_1[df['survived']==0]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
2,1,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,0
7,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S,0
9,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,0
...,...,...,...,...,...,...,...,...,...,...,...
312,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C,0
313,1,"Widener, Mr. Harry Elkins",male,27.0,0,2,113503,211.5000,C82,C,0
316,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C,0
318,1,"Williams-Lambert, Mr. Fletcher Fellows",male,NaN,0,0,113510,35.0000,C128,S,0
321,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S,0

In [32]:
#passengers who survied in pclass 1
survied_p1=p_class_1[df['survived']==1]

/tmp/ipykernel_4192/1190760186.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  survied_p1=p_class_1[df['survived']==1]

In [33]:
count_of_total=p_class_1['survived'].count()
count_of_survived=p_class_1[p_class_1['survived']==1]['survived'].count()
count_of_dead=p_class_1[p_class_1['survived']==0]['survived'].count()
survied_p1_percentage=(count_of_survived/count_of_total)*100

(count_of_dead/count_of_total)*100
survied_p1_percentage

np.float64(61.91950464396285)

In [34]:
#passengers whose age is below 30 or they are male
df[(df['age']<30)|(df['sex']=='male')]
# female passengers who died in titanic
df[(df['sex']=='female')& (df['survived']==0)]
#male passengers from pclass 3 who paid more then 100 as fare
df[(df['sex']=='male')&(df['pclass']==3)&(df['fare']>100)]

Empty DataFrame
Columns: [pclass, name, sex, age, sibsp, parch, ticket, fare, cabin, embarked, survived]
Index: []

In [35]:
#loc()--> labelled indexing
# it is used ti access the records using row index and
#syntax--> df.loc[[row1,row2,row3],[column name]]
'''
In the Python pandas library, df.loc[] is a label-based indexing property used to select,
filter, and update rows and columns in a DataFrame.
Instead of counting numerical positions (like 0, 1, 2),
you use actual row and column names (labels)
'''

df.loc[1,['name']]
df.loc[:,['name']]

#iloc--> integer location
#it is used to access / slice the dataframe using integer values.
#syntax--> df.iloc[row slice,col slice]

df.iloc[2:10:2,2:4]

      sex   age
2  female   2.0
4  female  25.0
6  female  63.0
8  female  53.0

In [36]:
# to check null valules
#syntax--> df[col].isnull()--> used to check missing/null values based on specific column
null=df[df['cabin'].isnull()]
null

df[df['cabin'].notnull()]
null

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
9,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,0
13,1,"Barber, Miss. Ellen ""Nellie""",female,26.0,0,0,19877,78.8500,NaN,S,1
15,1,"Baumann, Mr. John D",male,NaN,0,0,PC 17318,25.9250,NaN,S,0
23,1,"Bidois, Miss. Rosalie",female,42.0,0,0,PC 17757,227.5250,NaN,C,1
25,1,"Birnbaum, Mr. Jakob",male,25.0,0,0,13905,26.0000,NaN,C,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,0

In [37]:
df2=pd.read_csv('amazon_fires.csv',encoding='ISO-8859-10')
df2

# incase while reading the file we get unicodeDecodeError we can fix it
# by using :-
#                encoding='character code'
# standard uniucode values are: 'ISO-8859-10','latin'

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [38]:
#Data cleaning steps
'''
1. Rename the columns
Syntax-->
    data={old:new}
    df.rename(columns=data)

2. dropping duplicates
syntax--> df.drop_duplicates()--> removes the duplicates values presents in df
--> if we want to remove duplicates based on any specific column
syntax--> df.drop_duplicates(subset=col)

3. changing values present in a column
syntax-->
          data={old:new}
          df[col]=df[col].map(data)
  --> changes the respective values with the new value in a column
4. applying inbuilt functions on a column
syntax-->
          df[col].str.func()

5. handling missing values

    a. removing null values
    syntax--> df.dropna() #removes all the values records from the dataset
    if we want to remove null records based on a specific col
    syntax--> df.dropna(subset='col')

NOTE==> we should remove null values only when it is less than 2.5% of the dataframe

    b. filling null values with any specifc value
    syntax--> df.fillna(mean/mode/median/specific value)

    c. filling null values by backward or forward fill
    syntax--> df[col].ffill()  # add previous data above null value
              df[col].bfill()  # add next data below the null value

6. rearranging the cols
syntax--> df=df[new col order]

7. resetting the index of dataframe
  syntax--> df.reset_index()

8. Dropping unwanted column
  syntax--> df.drop(col,axis=1)

9.dropping unwanted rows
  syntax--> df.drop([1,2,3,4])

10. setting a column as index
  syntax--> df.set_index(col)
'''

"\n1. Rename the columns\nSyntax-->\n    data={old:new}\n    df.rename(columns=data)\n\n2. dropping duplicates\nsyntax--> df.drop_duplicates()--> removes the duplicates values presents in df\n--> if we want to remove duplicates based on any specific column\nsyntax--> df.drop_duplicates(subset=col)\n\n3. changing values present in a column\nsyntax-->\n          data={old:new}\n          df[col]=df[col].map(data)\n  --> changes the respective values with the new value in a column\n4. applying inbuilt functions on a column\nsyntax-->\n          df[col].str.func()\n\n5. handling missing values\n\n    a. removing null values\n    syntax--> df.dropna() #removes all the values records from the dataset\n    if we want to remove null records based on a specific col\n    syntax--> df.dropna(subset='col')\n\nNOTE==> we should remove null values only when it is less than 2.5% of the dataframe\n\n    b. filling null values with any specifc value\n    syntax--> df.fillna(mean/mode/median/specific value)\n\n    c. filling null values by backward or forward fill\n    syntax--> df[col].ffill()  # add previous data above null value\n              df[col].bfill()  # add next data below the null value\n\n6. rearranging the cols\nsyntax--> df=df[new col order]\n\n7. resetting the index of dataframe\n  syntax--> df.reset_index()\n\n8. Dropping unwanted column\n  syntax--> df.drop(col,axis=1)\n\n9.dropping unwanted rows\n  syntax--> df.drop([1,2,3,4])\n\n10. setting a column as index\n  syntax--> df.set_index(col)\n"

In [39]:
data={'ano':'Year','mes':'Month','estado':'State','numero':'No of fires','encontro':'Date'}
df2.rename(columns=data,inplace=True)
df2

      Year     Month      State No of fires      Date
0     1998   Janeiro       Acre     0 Fires  1/1/1998
1     1999   Janeiro       Acre     0 Fires  1/1/1999
2     2000   Janeiro       Acre     0 Fires  1/1/2000
3     2001   Janeiro       Acre     0 Fires  1/1/2001
4     2002   Janeiro       Acre     0 Fires  1/1/2002
...    ...       ...        ...         ...       ...
6449  2012  Dezembro  Tocantins         128  1/1/2012
6450  2013  Dezembro  Tocantins          85  1/1/2013
6451  2014  Dezembro  Tocantins         223  1/1/2014
6452  2015  Dezembro  Tocantins         373  1/1/2015
6453  2016  Dezembro  Tocantins         119  1/1/2016

[6454 rows x 5 columns]

In [40]:
df2.drop_duplicates()

      Year     Month      State No of fires      Date
0     1998   Janeiro       Acre     0 Fires  1/1/1998
1     1999   Janeiro       Acre     0 Fires  1/1/1999
2     2000   Janeiro       Acre     0 Fires  1/1/2000
3     2001   Janeiro       Acre     0 Fires  1/1/2001
4     2002   Janeiro       Acre     0 Fires  1/1/2002
...    ...       ...        ...         ...       ...
6449  2012  Dezembro  Tocantins         128  1/1/2012
6450  2013  Dezembro  Tocantins          85  1/1/2013
6451  2014  Dezembro  Tocantins         223  1/1/2014
6452  2015  Dezembro  Tocantins         373  1/1/2015
6453  2016  Dezembro  Tocantins         119  1/1/2016

[6424 rows x 5 columns]

In [41]:
df.drop_duplicates()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [42]:
df2['Month'].unique()

data={'Janeiro':'january', 'Fevereiro':'february', 'Marįo':'march', 'Abril':'april', 'Maio':'may', 'Junho':'june', 'Julho':'july',
       'Agosto':'august', 'Setembro':'september', 'Outubro':'october', 'Novembro':'november', 'Dezembro':'december'}

df2['Month']=df2['Month'].map(data)
df2

      Year     Month      State No of fires      Date
0     1998   january       Acre     0 Fires  1/1/1998
1     1999   january       Acre     0 Fires  1/1/1999
2     2000   january       Acre     0 Fires  1/1/2000
3     2001   january       Acre     0 Fires  1/1/2001
4     2002   january       Acre     0 Fires  1/1/2002
...    ...       ...        ...         ...       ...
6449  2012  december  Tocantins         128  1/1/2012
6450  2013  december  Tocantins          85  1/1/2013
6451  2014  december  Tocantins         223  1/1/2014
6452  2015  december  Tocantins         373  1/1/2015
6453  2016  december  Tocantins         119  1/1/2016

[6454 rows x 5 columns]

In [43]:
df2['No of fires']=df2['No of fires'].str.strip('Fires')

In [44]:
df2=df2[['Date','Year','Month','State','No of fires']]
df2

          Date  Year     Month      State No of fires
0     1/1/1998  1998   january       Acre          0
1     1/1/1999  1999   january       Acre          0
2     1/1/2000  2000   january       Acre          0
3     1/1/2001  2001   january       Acre          0
4     1/1/2002  2002   january       Acre          0
...        ...   ...       ...        ...         ...
6449  1/1/2012  2012  december  Tocantins         128
6450  1/1/2013  2013  december  Tocantins          85
6451  1/1/2014  2014  december  Tocantins         223
6452  1/1/2015  2015  december  Tocantins         373
6453  1/1/2016  2016  december  Tocantins         119

[6454 rows x 5 columns]

In [45]:
df2.reset_index(inplace=True)
df2

      index      Date  Year     Month      State No of fires
0         0  1/1/1998  1998   january       Acre          0
1         1  1/1/1999  1999   january       Acre          0
2         2  1/1/2000  2000   january       Acre          0
3         3  1/1/2001  2001   january       Acre          0
4         4  1/1/2002  2002   january       Acre          0
...     ...       ...   ...       ...        ...         ...
6449   6449  1/1/2012  2012  december  Tocantins         128
6450   6450  1/1/2013  2013  december  Tocantins          85
6451   6451  1/1/2014  2014  december  Tocantins         223
6452   6452  1/1/2015  2015  december  Tocantins         373
6453   6453  1/1/2016  2016  december  Tocantins         119

[6454 rows x 6 columns]

In [46]:
df3=pd.read_csv('https://raw.githubusercontent.com/sam6cyber/Datasets/refs/heads/main/hr_data.csv')
df3

#categorical column --> these are the columns which have very less
# no of unique values

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [47]:
#group by
'''
whenever we need data based on specific categorical column we use groupby

syntax--> pd.groupby([cat coll1,cat coll2, cat coll3, cat coll4])'''

'\nwhenever we need data based on specific categorical column we use groupby\n\nsyntax--> pd.groupby([cat coll1,cat coll2, cat coll3, cat coll4])'

In [48]:
dept=df3.groupby('department')

dept.get_group('IT')

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
61,1399,7,308,4,0,1,0,IT,medium
62,1404,6,244,5,0,1,0,IT,medium
63,1413,2,132,3,0,1,0,IT,medium
64,42423,6,286,4,0,1,0,IT,medium
65,1424,6,161,4,0,1,0,IT,medium
...,...,...,...,...,...,...,...,...,...
14930,87284,6,268,4,0,1,0,IT,medium
14931,87288,5,240,5,0,1,0,IT,medium
14932,87294,2,127,3,0,1,0,IT,medium
14933,87308,7,264,4,0,1,0,IT,medium
14938,45511,4,271,5,0,1,0,IT,medium

In [49]:
# avg monthly hours by each department
df3.groupby('department')['average_montly_hours'].mean()

#avg monthly hrs for it department
df3.groupby('department').get_group('IT')['average_montly_hours'].mean()

df3.groupby('department')['average_montly_hours'].mean().head(3)

department
IT            202.215974
RandD         200.800508
accounting    201.162973
Name: average_montly_hours, dtype: float64

In [50]:
#find the employees in support dept who left the company
df3[(df3['department']=='support')& (df3['left']==1)]
#or
df3.groupby(['department','left']).get_group(('support',1))
#find the employees those who are getting low salary working in it dept
df3[(df3['salary']=='low')&(df3['department']=='IT')]
#or
df3.groupby(['department','salary']).get_group(('IT','low'))
#find the maximum number of projects done by each dept
df3.groupby('department')['number_project'].max()

department
IT             7
RandD          7
accounting     7
hr             7
management     7
marketing      7
product_mng    7
sales          7
support        7
technical      7
Name: number_project, dtype: int64

In [51]:
#.agg()--> it is used ti apply multiple function on the dataframe
#syntax--> agg([func1,func2,func3,...funcN])

# using it in groupby
#df.groupby(cat col)[col].agg([func1,func2,func3,func4...])

In [52]:
'''
JOINS
-> It is used to combine two or more dataframes based on common column or index.

-> In real time datas are stored in different tables so joins plays an important role in combining multiple tables.

TYPES OF JOINS
INNER JOIN
OUTER JOIN
LEFT JOIN
RIGHT JOIN
CROSS JOIN

To perform joins we use some methods:-
    concat()--> used to concat two dataframes
    merge()--> used to merge two dataframes on common column

    '''

#concat()
#syntax--> pd.concat(df1,df2,axis=)

'\nJOINS\n-> It is used to combine two or more dataframes based on common column or index.\n\n-> In real time datas are stored in different tables so joins plays an important role in combining multiple tables.\n\nTYPES OF JOINS\nINNER JOIN\nOUTER JOIN\nLEFT JOIN\nRIGHT JOIN\nCROSS JOIN\n\nTo perform joins we use some methods:-\n    concat()--> used to concat two dataframes\n    merge()--> used to merge two dataframes on common column\n\n    '

In [53]:
employees = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Henry"],
    "Dept_ID": [1, 2, 1, 3, 2, 4, 5, 6],
    "Salary": [60000, 55000, 72000, 65000, 58000, 70000, 52000, 68000]
})

In [54]:
departments = pd.DataFrame({
    "Dept_ID": [1, 2, 3, 4, 7],
    "Department": [
        "HR",
        "Finance",
        "IT",
        "Marketing",
        "Legal"
    ],
    "Location": [
        "Hyderabad",
        "Bangalore",
        "Chennai",
        "Mumbai",
        "Delhi"
    ]
})

In [55]:
pd.concat((employees,departments),axis=1)

   Emp_ID     Name  Dept_ID  Salary  Dept_ID Department   Location
0     101    Alice        1   60000      1.0         HR  Hyderabad
1     102      Bob        2   55000      2.0    Finance  Bangalore
2     103  Charlie        1   72000      3.0         IT    Chennai
3     104    David        3   65000      4.0  Marketing     Mumbai
4     105      Eva        2   58000      7.0      Legal      Delhi
5     106    Frank        4   70000      NaN        NaN        NaN
6     107    Grace        5   52000      NaN        NaN        NaN
7     108    Henry        6   68000      NaN        NaN        NaN

In [56]:
pd.concat((employees,departments),axis=0)

   Emp_ID     Name  Dept_ID   Salary Department   Location
0   101.0    Alice        1  60000.0        NaN        NaN
1   102.0      Bob        2  55000.0        NaN        NaN
2   103.0  Charlie        1  72000.0        NaN        NaN
3   104.0    David        3  65000.0        NaN        NaN
4   105.0      Eva        2  58000.0        NaN        NaN
5   106.0    Frank        4  70000.0        NaN        NaN
6   107.0    Grace        5  52000.0        NaN        NaN
7   108.0    Henry        6  68000.0        NaN        NaN
0     NaN      NaN        1      NaN         HR  Hyderabad
1     NaN      NaN        2      NaN    Finance  Bangalore
2     NaN      NaN        3      NaN         IT    Chennai
3     NaN      NaN        4      NaN  Marketing     Mumbai
4     NaN      NaN        7      NaN      Legal      Delhi

In [57]:
#merge()
#syntax--> pd.merge(left,right,on='common col',how='join)
pd.merge(employees,departments,on='Dept_ID',how='inner')

   Emp_ID     Name  Dept_ID  Salary Department   Location
0     101    Alice        1   60000         HR  Hyderabad
1     102      Bob        2   55000    Finance  Bangalore
2     103  Charlie        1   72000         HR  Hyderabad
3     104    David        3   65000         IT    Chennai
4     105      Eva        2   58000    Finance  Bangalore
5     106    Frank        4   70000  Marketing     Mumbai

In [58]:
#inner join
#-> it joins the common records from both left and right table
#syntax--> pd.merge(left,right,on='common col',how='inner')

pd.merge(employees,departments,on='Dept_ID',how='inner')

   Emp_ID     Name  Dept_ID  Salary Department   Location
0     101    Alice        1   60000         HR  Hyderabad
1     102      Bob        2   55000    Finance  Bangalore
2     103  Charlie        1   72000         HR  Hyderabad
3     104    David        3   65000         IT    Chennai
4     105      Eva        2   58000    Finance  Bangalore
5     106    Frank        4   70000  Marketing     Mumbai

In [ ]:
#outer join
#--> it joins both dataframe based on matched as well as unmatched records
#syntax--> pd.merge(left,right,on='common col',how='outer')

In [59]:
pd.merge(employees,departments,on='Dept_ID',how='outer')

   Emp_ID     Name  Dept_ID   Salary Department   Location
0   101.0    Alice        1  60000.0         HR  Hyderabad
1   103.0  Charlie        1  72000.0         HR  Hyderabad
2   102.0      Bob        2  55000.0    Finance  Bangalore
3   105.0      Eva        2  58000.0    Finance  Bangalore
4   104.0    David        3  65000.0         IT    Chennai
5   106.0    Frank        4  70000.0  Marketing     Mumbai
6   107.0    Grace        5  52000.0        NaN        NaN
7   108.0    Henry        6  68000.0        NaN        NaN
8     NaN      NaN        7      NaN      Legal      Delhi

In [60]:
# left join
#--> it will join all the records of left dataframe and join all
# the matched records for the right dataframe

#syntax--> pd.merge(left,right,on='common col',how='left')
pd.merge(employees,departments,on='Dept_ID',how='left')

   Emp_ID     Name  Dept_ID  Salary Department   Location
0     101    Alice        1   60000         HR  Hyderabad
1     102      Bob        2   55000    Finance  Bangalore
2     103  Charlie        1   72000         HR  Hyderabad
3     104    David        3   65000         IT    Chennai
4     105      Eva        2   58000    Finance  Bangalore
5     106    Frank        4   70000  Marketing     Mumbai
6     107    Grace        5   52000        NaN        NaN
7     108    Henry        6   68000        NaN        NaN

In [61]:
#right join
#--> it will join all the records of right dataframe and join all
# the matched records for the left dataframe

#syntax--> pd.merge(left,right,on='common col',how='left')
pd.merge(employees,departments,on='Dept_ID',how='right')

   Emp_ID     Name  Dept_ID   Salary Department   Location
0   101.0    Alice        1  60000.0         HR  Hyderabad
1   103.0  Charlie        1  72000.0         HR  Hyderabad
2   102.0      Bob        2  55000.0    Finance  Bangalore
3   105.0      Eva        2  58000.0    Finance  Bangalore
4   104.0    David        3  65000.0         IT    Chennai
5   106.0    Frank        4  70000.0  Marketing     Mumbai
6     NaN      NaN        7      NaN      Legal      Delhi

In [63]:
#cross join
#-> it will join both dataframe by every possible combination
#syntax--> pd.merge(left,right,how='cross')

pd.merge(employees,departments,how='cross')

    Emp_ID     Name  Dept_ID_x  Salary  Dept_ID_y Department   Location
0      101    Alice          1   60000          1         HR  Hyderabad
1      101    Alice          1   60000          2    Finance  Bangalore
2      101    Alice          1   60000          3         IT    Chennai
3      101    Alice          1   60000          4  Marketing     Mumbai
4      101    Alice          1   60000          7      Legal      Delhi
5      102      Bob          2   55000          1         HR  Hyderabad
6      102      Bob          2   55000          2    Finance  Bangalore
7      102      Bob          2   55000          3         IT    Chennai
8      102      Bob          2   55000          4  Marketing     Mumbai
9      102      Bob          2   55000          7      Legal      Delhi
10     103  Charlie          1   72000          1         HR  Hyderabad
11     103  Charlie          1   72000          2    Finance  Bangalore
12     103  Charlie          1   72000          3         IT    Chennai
13     103  Charlie          1   72000          4  Marketing     Mumbai
14     103  Charlie          1   72000          7      Legal      Delhi
15     104    David          3   65000          1         HR  Hyderabad
16     104    David          3   65000          2    Finance  Bangalore
17     104    David          3   65000          3         IT    Chennai
18     104    David          3   65000          4  Marketing     Mumbai
19     104    David          3   65000          7      Legal      Delhi
20     105      Eva          2   58000          1         HR  Hyderabad
21     105      Eva          2   58000          2    Finance  Bangalore
22     105      Eva          2   58000          3         IT    Chennai
23     105      Eva          2   58000          4  Marketing     Mumbai
24     105      Eva          2   58000          7      Legal      Delhi
25     106    Frank          4   70000          1         HR  Hyderabad
26     106    Frank          4   70000          2    Finance  Bangalore
27     106    Frank          4   70000          3         IT    Chennai
28     106    Frank          4   70000          4  Marketing     Mumbai
29     106    Frank          4   70000          7      Legal      Delhi
30     107    Grace          5   52000          1         HR  Hyderabad
31     107    Grace          5   52000          2    Finance  Bangalore
32     107    Grace          5   52000          3         IT    Chennai
33     107    Grace          5   52000          4  Marketing     Mumbai
34     107    Grace          5   52000          7      Legal      Delhi
35     108    Henry          6   68000          1         HR  Hyderabad
36     108    Henry          6   68000          2    Finance  Bangalore
37     108    Henry          6   68000          3         IT    Chennai
38     108    Henry          6   68000          4  Marketing     Mumbai
39     108    Henry          6   68000          7      Legal      Delhi

In [71]:
df3

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [100]:
# Find the number of employees in each department.
df3.groupby('department')['employee_id'].count()
# Find the average monthly working hours for each department.
df3.groupby('department')['average_montly_hours'].mean()
# Find the maximum monthly working hours in each department.
df3.groupby('department')['average_montly_hours'].max()
# Find the minimum monthly working hours in each department.
df3.groupby('department')['average_montly_hours'].min()
# Find the average time spent in the company for each department.
df3.groupby('department')['time_spend_company'].mean()
# Find the highest number of projects in each department.
df3.groupby('department')['number_project'].max()
# Find the employee count for each department based on whether they left (left).
df3.groupby(['department','left']).count()
# df3.groupby('department')['left']
# Find the average company experience grouped by department and left.

# Find the average monthly hours of employees who left in each department.
# Find the average number of projects handled by employees who left.


# Count employees who had a work accident in each department.
# Find the average monthly hours of employees with work accidents.
# Compare average projects between employees with and without work accidents.

                  employee_id  number_project  average_montly_hours  \
department  left
IT          0             954             954                   954
            1             273             273                   273
RandD       0             666             666                   666
            1             121             121                   121
accounting  0             563             563                   563
            1             204             204                   204
hr          0             524             524                   524
            1             215             215                   215
management  0             539             539                   539
            1              91              91                    91
marketing   0             655             655                   655
            1             203             203                   203
product_mng 0             704             704                   704
            1             198             198                   198
sales       0            3126            3126                  3126
            1            1014            1014                  1014
support     0            1674            1674                  1674
            1             555             555                   555
technical   0            2023            2023                  2023
            1             697             697                   697

                  time_spend_company  Work_accident  promotion_last_5years  \
department  left
IT          0                    954            954                    954
            1                    273            273                    273
RandD       0                    666            666                    666
            1                    121            121                    121
accounting  0                    563            563                    563
            1                    204            204                    204
hr          0                    524            524                    524
            1                    215            215                    215
management  0                    539            539                    539
            1                     91             91                     91
marketing   0                    655            655                    655
            1                    203            203                    203
product_mng 0                    704            704                    704
            1                    198            198                    198
sales       0                   3126           3126                   3126
            1                   1014           1014                   1014
support     0                   1674           1674                   1674
            1                    555            555                    555
technical   0                   2023           2023                   2023
            1                    697            697                    697

                  salary
department  left
IT          0        954
            1        273
RandD       0        666
            1        121
accounting  0        563
            1        204
hr          0        524
            1        215
management  0        539
            1         91
marketing   0        655
            1        203
product_mng 0        704
            1        198
sales       0       3126
            1       1014
support     0       1674
            1        555
technical   0       2023
            1        697

In [ ]:
## pivot table
'''
it is a way of summarizing the data based on categories.
--> in pivot table it makes large dataset to convert into smaller summary table which helps to answer business questions
--> it also known as powerhouse of pandas as we can perfrom multiple agg functions on multiple column at a same time '''

In [ ]:
#syntax-->
  # pd.pivot_table(data=df,values,index='cat col',aggfunc=[func1,func2,...,funcn])

    # df.pivot_table(values,index='cat col',aggfunc=[func1,func2,...,funcn])

In [108]:
df4 = pd.DataFrame({
"Department": ["IT", "IT", "HR", "HR", "Sales", "Sales"],
"Gender": ["Male", "Female", "Male", "Female", "Male", "Female"],
"Salary": [60000, 70000, 50000, 55000, 45000, 50000]
})
df4

  Department  Gender  Salary
0         IT    Male   60000
1         IT  Female   70000
2         HR    Male   50000
3         HR  Female   55000
4      Sales    Male   45000
5      Sales  Female   50000

In [110]:
# df4.pivot_table()

In [111]:
df5=pd.read_csv('https://raw.githubusercontent.com/sam6cyber/Datasets/refs/heads/main/blinkit_data.csv')
df5

,Unnamed: 0,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
0,0,Regular,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.100014,15.100000,145.4786,5.0
1,1,Low Fat,NCB42,Health and Hygiene,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.008596,11.800000,115.3492,5.0
2,2,Regular,FDR28,Frozen Foods,2016,OUT046,Tier 1,Small,Supermarket Type1,0.025896,13.850000,165.0210,5.0
3,3,Regular,FDL50,Canned,2014,OUT013,Tier 3,High,Supermarket Type1,0.042278,12.150000,126.5046,5.0
4,4,Low Fat,DRI25,Soft Drinks,2015,OUT045,Tier 2,Small,Supermarket Type1,0.033970,19.600000,55.1614,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,8518,Low Fat,NCT53,Health and Hygiene,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.000000,12.857645,164.5526,4.0
8519,8519,Low Fat,FDN09,Snack Foods,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.034706,12.857645,241.6828,4.0
8520,8520,Low Fat,DRE13,Soft Drinks,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.027571,12.857645,86.6198,4.0
8521,8521,Regular,FDT50,Dairy,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.107715,12.857645,97.8752,4.0
8522,8522,Regular,FDM58,Snack Foods,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.000000,12.857645,112.2544,4.0

In [114]:
df5.pivot_table(values='Sales',index='Item Type',columns='Outlet Location Type',aggfunc=['min','max'])

                           min                         max
Outlet Location Type    Tier 1   Tier 2   Tier 3    Tier 1    Tier 2    Tier 3
Item Type
Baking Goods           35.0874  35.0874  33.9874  263.8568  265.5568  265.1568
Breads                 33.3558  33.6874  31.9558  263.1594  262.7594  263.6594
Breakfast              40.0480  41.6480  40.3480  232.7300  234.9300  233.9300
Canned                 37.8506  36.3506  37.4506  266.8884  266.8884  266.1884
Dairy                  36.1874  34.4874  33.4874  266.1884  265.2568  266.6884
Frozen Foods           32.8558  32.0558  31.9558  264.4910  264.3910  264.8910
Fruits and Vegetables  36.2506  36.4848  36.6506  262.6252  264.2252  263.9252
Hard Drinks            36.2506  34.9532  34.2532  261.0278  251.5040  261.4278
Health and Hygiene     33.1216  33.5874  33.2874  266.2884  266.5884  266.6884
Household              32.4558  33.3558  33.2216  263.6910  264.7910  263.7910
Meat                   35.1532  36.6532  34.7532  250.9408  261.5936  256.0330
Others                 36.4190  35.5190  35.0190  254.9040  254.0040  241.2538
Seafood                34.2216  33.9216  33.7216  240.2880  239.9880  240.1880
Snack Foods            34.9558  33.1558  32.3558  264.7568  264.9568  264.9568
Soft Drinks            32.4900  32.0900  31.2900  261.2910  263.5910  263.1910
Starchy Foods          34.6532  36.6532  34.0532  260.3252  262.8252  263.0252